name: to_do_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: any
  font_awesome_flutter: any
  google_fonts: any
  hive: any
  hive_flutter: any
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  build_runner: any
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: any

flutter:
  uses-material-design: true
