name: to_do_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  hive : any
  hive_flutter : any
  google_fonts : any
  font_awesome_flutter : any
  flutter_bloc : any
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner : any
  hive_generator : any

flutter:
  uses-material-design: true
